/*****************************************************************************
*                                                                            *
*  OpenNI 1.x Alpha                                                          *
*  Copyright (C) 2012 PrimeSense Ltd.                                        *
*                                                                            *
*  This file is part of OpenNI.                                              *
*                                                                            *
*  Licensed under the Apache License, Version 2.0 (the "License");           *
*  you may not use this file except in compliance with the License.          *
*  You may obtain a copy of the License at                                   *
*                                                                            *
*      http://www.apache.org/licenses/LICENSE-2.0                            *
*                                                                            *
*  Unless required by applicable law or agreed to in writing, software       *
*  distributed under the License is distributed on an "AS IS" BASIS,         *
*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  *
*  See the License for the specific language governing permissions and       *
*  limitations under the License.                                            *
*                                                                            *
*****************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openni_NativeMethods */

#ifndef _Included_org_openni_NativeMethods
#define _Included_org_openni_NativeMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openni_NativeMethods
 * Method:    readByte
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_org_openni_NativeMethods_readByte
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    readShort
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_org_openni_NativeMethods_readShort
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    readInt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_readInt
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    readLong
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_openni_NativeMethods_readLong
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    copyToBuffer
 * Signature: (Ljava/nio/ByteBuffer;JI)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_copyToBuffer
  (JNIEnv *, jclass, jobject, jlong, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    createProductionNodeDescription
 * Signature: (ILjava/lang/String;Ljava/lang/String;BBSI)J
 */
JNIEXPORT jlong JNICALL Java_org_openni_NativeMethods_createProductionNodeDescription
  (JNIEnv *, jclass, jint, jstring, jstring, jbyte, jbyte, jshort, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    freeProductionNodeDescription
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_freeProductionNodeDescription
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetStatusString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_openni_NativeMethods_xnGetStatusString
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnInit
 * Signature: (Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnInit
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnContextRunXmlScriptFromFileEx
 * Signature: (JLjava/lang/String;JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnContextRunXmlScriptFromFileEx
  (JNIEnv *, jclass, jlong, jstring, jlong, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnContextRunXmlScriptEx
 * Signature: (JLjava/lang/String;JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnContextRunXmlScriptEx
  (JNIEnv *, jclass, jlong, jstring, jlong, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnInitFromXmlFileEx
 * Signature: (Ljava/lang/String;Lorg/openni/OutArg;JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnInitFromXmlFileEx
  (JNIEnv *, jclass, jstring, jobject, jlong, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnContextOpenFileRecordingEx
 * Signature: (JLjava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnContextOpenFileRecordingEx
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnContextAddRef
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnContextAddRef
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnContextRelease
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnContextRelease
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnEnumerateProductionTrees
 * Signature: (JIJLorg/openni/OutArg;J)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnEnumerateProductionTrees
  (JNIEnv *, jclass, jlong, jint, jlong, jobject, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnCreateProductionTree
 * Signature: (JJLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnCreateProductionTree
  (JNIEnv *, jclass, jlong, jlong, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnCreateAnyProductionTree
 * Signature: (JIJLorg/openni/OutArg;J)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnCreateAnyProductionTree
  (JNIEnv *, jclass, jlong, jint, jlong, jobject, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnEnumerateExistingNodes
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnEnumerateExistingNodes
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnEnumerateExistingNodesByType
 * Signature: (JILorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnEnumerateExistingNodesByType
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnFindExistingRefNodeByType
 * Signature: (JILorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnFindExistingRefNodeByType
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetRefNodeHandleByName
 * Signature: (JLjava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetRefNodeHandleByName
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnWaitAndUpdateAll
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnWaitAndUpdateAll
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnWaitOneUpdateAll
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnWaitOneUpdateAll
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnWaitAnyUpdateAll
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnWaitAnyUpdateAll
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnWaitNoneUpdateAll
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnWaitNoneUpdateAll
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnStartGeneratingAll
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnStartGeneratingAll
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnStopGeneratingAll
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnStopGeneratingAll
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnSetGlobalMirror
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnSetGlobalMirror
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetGlobalMirror
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openni_NativeMethods_xnGetGlobalMirror
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetGlobalErrorState
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetGlobalErrorState
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnRegisterToGlobalErrorStateChange
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnRegisterToGlobalErrorStateChange
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnUnregisterFromGlobalErrorStateChange
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnUnregisterFromGlobalErrorStateChange
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnRegisterToNodeCreation
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnRegisterToNodeCreation
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnUnregisterFromNodeCreation
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnUnregisterFromNodeCreation
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnRegisterToNodeDestruction
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnRegisterToNodeDestruction
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnUnregisterFromNodeDestruction
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnUnregisterFromNodeDestruction
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnAddLicense
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnAddLicense
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnEnumerateLicenses
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnEnumerateLicenses
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnEnumerationErrorsAllocate
 * Signature: (Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnEnumerationErrorsAllocate
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnEnumerationErrorsFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnEnumerationErrorsFree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnEnumerationErrorsToString
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnEnumerationErrorsToString
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnEnumerationErrorsClear
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnEnumerationErrorsClear
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnEnumerationErrorsGetFirst
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_openni_NativeMethods_xnEnumerationErrorsGetFirst
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnEnumerationErrorsIteratorIsValid
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openni_NativeMethods_xnEnumerationErrorsIteratorIsValid
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnNodeInfoSetInstanceName
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnNodeInfoSetInstanceName
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnNodeInfoGetDescription
 * Signature: (J)Lorg/openni/ProductionNodeDescription;
 */
JNIEXPORT jobject JNICALL Java_org_openni_NativeMethods_xnNodeInfoGetDescription
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnNodeInfoGetTreeStringRepresentation
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnNodeInfoGetTreeStringRepresentation
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnNodeInfoGetInstanceName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_openni_NativeMethods_xnNodeInfoGetInstanceName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnNodeInfoGetCreationInfo
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_openni_NativeMethods_xnNodeInfoGetCreationInfo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnNodeInfoGetNeededNodes
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_openni_NativeMethods_xnNodeInfoGetNeededNodes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnNodeInfoGetRefHandle
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_openni_NativeMethods_xnNodeInfoGetRefHandle
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnNodeInfoListAllocate
 * Signature: (Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnNodeInfoListAllocate
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnNodeInfoListFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnNodeInfoListFree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnNodeInfoListAdd
 * Signature: (JJLjava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnNodeInfoListAdd
  (JNIEnv *, jclass, jlong, jlong, jstring, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnNodeInfoListAddNode
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnNodeInfoListAddNode
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnNodeInfoListAddNodeFromList
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnNodeInfoListAddNodeFromList
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnNodeInfoListRemove
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnNodeInfoListRemove
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnNodeInfoListClear
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnNodeInfoListClear
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnNodeInfoListAppend
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnNodeInfoListAppend
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnNodeInfoListIsEmpty
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openni_NativeMethods_xnNodeInfoListIsEmpty
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnNodeInfoListGetFirst
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_openni_NativeMethods_xnNodeInfoListGetFirst
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnNodeInfoListIteratorIsValid
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openni_NativeMethods_xnNodeInfoListIteratorIsValid
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnNodeInfoListGetCurrent
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_openni_NativeMethods_xnNodeInfoListGetCurrent
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnNodeInfoListGetNext
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_openni_NativeMethods_xnNodeInfoListGetNext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnNodeQueryAllocate
 * Signature: (Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnNodeQueryAllocate
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnNodeQueryFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnNodeQueryFree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnNodeQuerySetVendor
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnNodeQuerySetVendor
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnNodeQuerySetName
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnNodeQuerySetName
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnNodeQuerySetMinVersion
 * Signature: (JBBSI)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnNodeQuerySetMinVersion
  (JNIEnv *, jclass, jlong, jbyte, jbyte, jshort, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnNodeQuerySetMaxVersion
 * Signature: (JBBSI)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnNodeQuerySetMaxVersion
  (JNIEnv *, jclass, jlong, jbyte, jbyte, jshort, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnNodeQueryAddSupportedCapability
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnNodeQueryAddSupportedCapability
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnNodeQueryAddSupportedMapOutputMode
 * Signature: (JIII)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnNodeQueryAddSupportedMapOutputMode
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnNodeQuerySetSupportedMinUserPositions
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnNodeQuerySetSupportedMinUserPositions
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnNodeQuerySetExistingNodeOnly
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnNodeQuerySetExistingNodeOnly
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnNodeQuerySetNonExistingNodeOnly
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnNodeQuerySetNonExistingNodeOnly
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnNodeQueryAddNeededNode
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnNodeQueryAddNeededNode
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnNodeQuerySetCreationInfo
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnNodeQuerySetCreationInfo
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnNodeQueryFilterList
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnNodeQueryFilterList
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnProductionNodeAddRef
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnProductionNodeAddRef
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnProductionNodeRelease
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnProductionNodeRelease
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetNodeInfo
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_openni_NativeMethods_xnGetNodeInfo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetNodeName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_openni_NativeMethods_xnGetNodeName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetRefContextFromNodeHandle
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_openni_NativeMethods_xnGetRefContextFromNodeHandle
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnIsCapabilitySupported
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openni_NativeMethods_xnIsCapabilitySupported
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnSetIntProperty
 * Signature: (JLjava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnSetIntProperty
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnSetRealProperty
 * Signature: (JLjava/lang/String;D)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnSetRealProperty
  (JNIEnv *, jclass, jlong, jstring, jdouble);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnSetStringProperty
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnSetStringProperty
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnSetGeneralProperty
 * Signature: (JLjava/lang/String;IJ)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnSetGeneralProperty
  (JNIEnv *, jclass, jlong, jstring, jint, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnSetGeneralPropertyArray
 * Signature: (JLjava/lang/String;[B)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnSetGeneralPropertyArray
  (JNIEnv *, jclass, jlong, jstring, jbyteArray);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetIntProperty
 * Signature: (JLjava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetIntProperty
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetRealProperty
 * Signature: (JLjava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetRealProperty
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetStringProperty
 * Signature: (JLjava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetStringProperty
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetGeneralProperty
 * Signature: (JLjava/lang/String;IJ)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetGeneralProperty
  (JNIEnv *, jclass, jlong, jstring, jint, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetGeneralPropertyArray
 * Signature: (JLjava/lang/String;[B)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetGeneralPropertyArray
  (JNIEnv *, jclass, jlong, jstring, jbyteArray);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnLockNodeForChanges
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnLockNodeForChanges
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnUnlockNodeForChanges
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnUnlockNodeForChanges
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnLockedNodeStartChanges
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnLockedNodeStartChanges
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnLockedNodeEndChanges
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnLockedNodeEndChanges
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnAddNeededNode
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnAddNeededNode
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnRemoveNeededNode
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnRemoveNeededNode
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnCreateDevice
 * Signature: (JLorg/openni/OutArg;JJ)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnCreateDevice
  (JNIEnv *, jclass, jlong, jobject, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetDeviceName
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetDeviceName
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetVendorSpecificData
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetVendorSpecificData
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetSerialNumber
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetSerialNumber
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetNodeErrorState
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetNodeErrorState
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnRegisterToNodeErrorStateChange
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnRegisterToNodeErrorStateChange
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnUnregisterFromNodeErrorStateChange
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnUnregisterFromNodeErrorStateChange
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetGeneralIntRange
 * Signature: (JLjava/lang/String;Lorg/openni/OutArg;Lorg/openni/OutArg;Lorg/openni/OutArg;Lorg/openni/OutArg;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetGeneralIntRange
  (JNIEnv *, jclass, jlong, jstring, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetGeneralIntValue
 * Signature: (JLjava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetGeneralIntValue
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnSetGeneralIntValue
 * Signature: (JLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnSetGeneralIntValue
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnRegisterToGeneralIntValueChange
 * Signature: (JLjava/lang/String;Ljava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnRegisterToGeneralIntValueChange
  (JNIEnv *, jclass, jlong, jstring, jobject, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnUnregisterFromGeneralIntValueChange
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnUnregisterFromGeneralIntValueChange
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnStartGenerating
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnStartGenerating
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnIsGenerating
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openni_NativeMethods_xnIsGenerating
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnStopGenerating
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnStopGenerating
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnRegisterToGenerationRunningChange
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnRegisterToGenerationRunningChange
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnUnregisterFromGenerationRunningChange
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnUnregisterFromGenerationRunningChange
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnRegisterToNewDataAvailable
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnRegisterToNewDataAvailable
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnUnregisterFromNewDataAvailable
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnUnregisterFromNewDataAvailable
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnIsNewDataAvailable
 * Signature: (JLorg/openni/OutArg;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openni_NativeMethods_xnIsNewDataAvailable
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnWaitAndUpdateData
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnWaitAndUpdateData
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnIsDataNew
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openni_NativeMethods_xnIsDataNew
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetData
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_openni_NativeMethods_xnGetData
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetDataSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetDataSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetTimestamp
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_openni_NativeMethods_xnGetTimestamp
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetFrameID
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetFrameID
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnSetMirror
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnSetMirror
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnIsMirrored
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openni_NativeMethods_xnIsMirrored
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnRegisterToMirrorChange
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnRegisterToMirrorChange
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnUnregisterFromMirrorChange
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnUnregisterFromMirrorChange
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnIsViewPointSupported
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openni_NativeMethods_xnIsViewPointSupported
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnSetViewPoint
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnSetViewPoint
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnResetViewPoint
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnResetViewPoint
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnIsViewPointAs
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openni_NativeMethods_xnIsViewPointAs
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnRegisterToViewPointChange
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnRegisterToViewPointChange
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnUnregisterFromViewPointChange
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnUnregisterFromViewPointChange
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetPixelCoordinatesInViewPoint
 * Signature: (JJIILorg/openni/OutArg;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetPixelCoordinatesInViewPoint
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jobject, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnCanFrameSyncWith
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openni_NativeMethods_xnCanFrameSyncWith
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnFrameSyncWith
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnFrameSyncWith
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnStopFrameSyncWith
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnStopFrameSyncWith
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnIsFrameSyncedWith
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openni_NativeMethods_xnIsFrameSyncedWith
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnRegisterToFrameSyncChange
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnRegisterToFrameSyncChange
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnUnregisterFromFrameSyncChange
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnUnregisterFromFrameSyncChange
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetSupportedMapOutputModesCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetSupportedMapOutputModesCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetSupportedMapOutputModes
 * Signature: (J[Lorg/openni/MapOutputMode;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetSupportedMapOutputModes
  (JNIEnv *, jclass, jlong, jobjectArray);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnSetMapOutputMode
 * Signature: (JIII)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnSetMapOutputMode
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetMapOutputMode
 * Signature: (JLorg/openni/OutArg;Lorg/openni/OutArg;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetMapOutputMode
  (JNIEnv *, jclass, jlong, jobject, jobject, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnRegisterToMapOutputModeChange
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnRegisterToMapOutputModeChange
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnUnregisterFromMapOutputModeChange
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnUnregisterFromMapOutputModeChange
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetBytesPerPixel
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetBytesPerPixel
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnSetCropping
 * Signature: (JIIIIZ)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnSetCropping
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jboolean);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetCropping
 * Signature: (JLorg/openni/OutArg;Lorg/openni/OutArg;Lorg/openni/OutArg;Lorg/openni/OutArg;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetCropping
  (JNIEnv *, jclass, jlong, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnRegisterToCroppingChange
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnRegisterToCroppingChange
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnUnregisterFromCroppingChange
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnUnregisterFromCroppingChange
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnSetPowerLineFrequency
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnSetPowerLineFrequency
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetPowerLineFrequency
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetPowerLineFrequency
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnRegisterToPowerLineFrequencyChange
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnRegisterToPowerLineFrequencyChange
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnUnregisterFromPowerLineFrequencyChange
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnUnregisterFromPowerLineFrequencyChange
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnCreateDepthGenerator
 * Signature: (JLorg/openni/OutArg;JJ)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnCreateDepthGenerator
  (JNIEnv *, jclass, jlong, jobject, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetDeviceMaxDepth
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_org_openni_NativeMethods_xnGetDeviceMaxDepth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetDepthFieldOfView
 * Signature: (JLorg/openni/OutArg;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetDepthFieldOfView
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnRegisterToDepthFieldOfViewChange
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnRegisterToDepthFieldOfViewChange
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnUnregisterFromDepthFieldOfViewChange
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnUnregisterFromDepthFieldOfViewChange
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnConvertProjectiveToRealWorld
 * Signature: (J[Lorg/openni/Point3D;[Lorg/openni/Point3D;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnConvertProjectiveToRealWorld
  (JNIEnv *, jclass, jlong, jobjectArray, jobjectArray);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnConvertRealWorldToProjective
 * Signature: (J[Lorg/openni/Point3D;[Lorg/openni/Point3D;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnConvertRealWorldToProjective
  (JNIEnv *, jclass, jlong, jobjectArray, jobjectArray);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetDepthMap
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_openni_NativeMethods_xnGetDepthMap
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetDepthMetaData
 * Signature: (JLorg/openni/DepthMetaData;)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnGetDepthMetaData
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetSupportedUserPositionsCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetSupportedUserPositionsCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnSetUserPosition
 * Signature: (JIFFFFFF)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnSetUserPosition
  (JNIEnv *, jclass, jlong, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetUserPosition
 * Signature: (JILorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetUserPosition
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnRegisterToUserPositionChange
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnRegisterToUserPositionChange
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnUnregisterFromUserPositionChange
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnUnregisterFromUserPositionChange
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnCreateImageGenerator
 * Signature: (JLorg/openni/OutArg;JJ)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnCreateImageGenerator
  (JNIEnv *, jclass, jlong, jobject, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetImageMap
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_openni_NativeMethods_xnGetImageMap
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnIsPixelFormatSupported
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openni_NativeMethods_xnIsPixelFormatSupported
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnSetPixelFormat
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnSetPixelFormat
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetPixelFormat
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetPixelFormat
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnRegisterToPixelFormatChange
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnRegisterToPixelFormatChange
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnUnregisterFromPixelFormatChange
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnUnregisterFromPixelFormatChange
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetImageMetaData
 * Signature: (JLorg/openni/ImageMetaData;)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnGetImageMetaData
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnCreateIRGenerator
 * Signature: (JLorg/openni/OutArg;JJ)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnCreateIRGenerator
  (JNIEnv *, jclass, jlong, jobject, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetIRMap
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_openni_NativeMethods_xnGetIRMap
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetIRMetaData
 * Signature: (JLorg/openni/IRMetaData;)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnGetIRMetaData
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnCreateGestureGenerator
 * Signature: (JLorg/openni/OutArg;JJ)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnCreateGestureGenerator
  (JNIEnv *, jclass, jlong, jobject, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnAddGesture
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnAddGesture__JLjava_lang_String_2
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnAddGesture
 * Signature: (JLjava/lang/String;FFFFFF)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnAddGesture__JLjava_lang_String_2FFFFFF
  (JNIEnv *, jclass, jlong, jstring, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnRemoveGesture
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnRemoveGesture
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetAllActiveGestures
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetAllActiveGestures
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetNumberOfAvailableGestures
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetNumberOfAvailableGestures
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnEnumerateAllGestures
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnEnumerateAllGestures
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnIsGestureAvailable
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openni_NativeMethods_xnIsGestureAvailable
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnIsGestureProgressSupported
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openni_NativeMethods_xnIsGestureProgressSupported
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnRegisterGestureCallbacks
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnRegisterGestureCallbacks
  (JNIEnv *, jclass, jlong, jobject, jstring, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnUnregisterGestureCallbacks
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnUnregisterGestureCallbacks
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnRegisterToGestureChange
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnRegisterToGestureChange
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnUnregisterFromGestureChange
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnUnregisterFromGestureChange
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnRegisterToGestureIntermediateStageCompleted
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnRegisterToGestureIntermediateStageCompleted
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnUnregisterFromGestureIntermediateStageCompleted
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnUnregisterFromGestureIntermediateStageCompleted
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnRegisterToGestureReadyForNextIntermediateStage
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnRegisterToGestureReadyForNextIntermediateStage
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnUnregisterFromGestureReadyForNextIntermediateStage
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnUnregisterFromGestureReadyForNextIntermediateStage
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnCreateSceneAnalyzer
 * Signature: (JLorg/openni/OutArg;JJ)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnCreateSceneAnalyzer
  (JNIEnv *, jclass, jlong, jobject, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetLabelMap
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_openni_NativeMethods_xnGetLabelMap
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetFloor
 * Signature: (JLorg/openni/OutArg;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetFloor
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetSceneMetaData
 * Signature: (JLorg/openni/SceneMetaData;)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnGetSceneMetaData
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnCreateUserGenerator
 * Signature: (JLorg/openni/OutArg;JJ)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnCreateUserGenerator
  (JNIEnv *, jclass, jlong, jobject, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetNumberOfUsers
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetNumberOfUsers
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetUsers
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetUsers
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetUserCoM
 * Signature: (JILorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetUserCoM
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetUserPixels
 * Signature: (JILorg/openni/SceneMetaData;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetUserPixels
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnRegisterUserCallbacks
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnRegisterUserCallbacks
  (JNIEnv *, jclass, jlong, jobject, jstring, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnUnregisterUserCallbacks
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnUnregisterUserCallbacks
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnRegisterToUserExit
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnRegisterToUserExit
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnUnregisterFromUserExit
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnUnregisterFromUserExit
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnRegisterToUserReEnter
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnRegisterToUserReEnter
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnUnregisterFromUserReEnter
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnUnregisterFromUserReEnter
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnIsJointAvailable
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openni_NativeMethods_xnIsJointAvailable
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnIsProfileAvailable
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openni_NativeMethods_xnIsProfileAvailable
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnSetSkeletonProfile
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnSetSkeletonProfile
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnSetJointActive
 * Signature: (JIZ)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnSetJointActive
  (JNIEnv *, jclass, jlong, jint, jboolean);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnIsJointActive
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openni_NativeMethods_xnIsJointActive
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnRegisterToJointConfigurationChange
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnRegisterToJointConfigurationChange
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnUnregisterFromJointConfigurationChange
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnUnregisterFromJointConfigurationChange
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnEnumerateActiveJoints
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnEnumerateActiveJoints
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetSkeletonJoint
 * Signature: (JIILorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetSkeletonJoint
  (JNIEnv *, jclass, jlong, jint, jint, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetSkeletonJointPosition
 * Signature: (JIILorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetSkeletonJointPosition
  (JNIEnv *, jclass, jlong, jint, jint, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetSkeletonJointOrientation
 * Signature: (JIILorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetSkeletonJointOrientation
  (JNIEnv *, jclass, jlong, jint, jint, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnIsSkeletonTracking
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openni_NativeMethods_xnIsSkeletonTracking
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnIsSkeletonCalibrated
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openni_NativeMethods_xnIsSkeletonCalibrated
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnIsSkeletonCalibrating
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openni_NativeMethods_xnIsSkeletonCalibrating
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnRequestSkeletonCalibration
 * Signature: (JIZ)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnRequestSkeletonCalibration
  (JNIEnv *, jclass, jlong, jint, jboolean);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnAbortSkeletonCalibration
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnAbortSkeletonCalibration
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnSaveSkeletonCalibrationDataToFile
 * Signature: (JILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnSaveSkeletonCalibrationDataToFile
  (JNIEnv *, jclass, jlong, jint, jstring);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnLoadSkeletonCalibrationDataFromFile
 * Signature: (JILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnLoadSkeletonCalibrationDataFromFile
  (JNIEnv *, jclass, jlong, jint, jstring);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnSaveSkeletonCalibrationData
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnSaveSkeletonCalibrationData
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnLoadSkeletonCalibrationData
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnLoadSkeletonCalibrationData
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnClearSkeletonCalibrationData
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnClearSkeletonCalibrationData
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnIsSkeletonCalibrationData
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openni_NativeMethods_xnIsSkeletonCalibrationData
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnStartSkeletonTracking
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnStartSkeletonTracking
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnStopSkeletonTracking
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnStopSkeletonTracking
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnResetSkeleton
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnResetSkeleton
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnNeedPoseForSkeletonCalibration
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openni_NativeMethods_xnNeedPoseForSkeletonCalibration
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetSkeletonCalibrationPose
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetSkeletonCalibrationPose
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnSetSkeletonSmoothing
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnSetSkeletonSmoothing
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnRegisterToCalibrationStart
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnRegisterToCalibrationStart
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnUnregisterFromCalibrationStart
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnUnregisterFromCalibrationStart
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnRegisterToCalibrationInProgress
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnRegisterToCalibrationInProgress
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnUnregisterFromCalibrationInProgress
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnUnregisterFromCalibrationInProgress
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnRegisterToCalibrationComplete
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnRegisterToCalibrationComplete
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnUnregisterFromCalibrationComplete
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnUnregisterFromCalibrationComplete
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetNumberOfPoses
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetNumberOfPoses
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetAllAvailablePoses
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetAllAvailablePoses
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnStartPoseDetection
 * Signature: (JLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnStartPoseDetection
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnStopPoseDetection
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnStopPoseDetection
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnStopSinglePoseDetection
 * Signature: (JILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnStopSinglePoseDetection
  (JNIEnv *, jclass, jlong, jint, jstring);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnRegisterToPoseDetected
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnRegisterToPoseDetected
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnUnregisterFromPoseDetected
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnUnregisterFromPoseDetected
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnRegisterToOutOfPose
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnRegisterToOutOfPose
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnUnregisterFromOutOfPose
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnUnregisterFromOutOfPose
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnRegisterToPoseDetectionInProgress
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnRegisterToPoseDetectionInProgress
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnUnregisterFromPoseDetectionInProgress
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnUnregisterFromPoseDetectionInProgress
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnIsPoseSupported
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openni_NativeMethods_xnIsPoseSupported
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetPoseStatus
 * Signature: (JILjava/lang/String;Lorg/openni/OutArg;Lorg/openni/OutArg;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetPoseStatus
  (JNIEnv *, jclass, jlong, jint, jstring, jobject, jobject, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnCreateHandsGenerator
 * Signature: (JLorg/openni/OutArg;JJ)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnCreateHandsGenerator
  (JNIEnv *, jclass, jlong, jobject, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnRegisterHandCallbacks
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnRegisterHandCallbacks
  (JNIEnv *, jclass, jlong, jobject, jstring, jstring, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnUnregisterHandCallbacks
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnUnregisterHandCallbacks
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnStopTracking
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnStopTracking
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnStopTrackingAll
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnStopTrackingAll
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnStartTracking
 * Signature: (JFFF)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnStartTracking
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnSetTrackingSmoothing
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnSetTrackingSmoothing
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnRegisterToHandTouchingFOVEdge
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnRegisterToHandTouchingFOVEdge
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnUnregisterFromHandTouchingFOVEdge
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnUnregisterFromHandTouchingFOVEdge
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnCreateAudioGenerator
 * Signature: (JLorg/openni/OutArg;JJ)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnCreateAudioGenerator
  (JNIEnv *, jclass, jlong, jobject, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetAudioBuffer
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_openni_NativeMethods_xnGetAudioBuffer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetSupportedWaveOutputModesCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetSupportedWaveOutputModesCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetSupportedWaveOutputModes
 * Signature: (J[Lorg/openni/WaveOutputMode;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetSupportedWaveOutputModes
  (JNIEnv *, jclass, jlong, jobjectArray);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnSetWaveOutputMode
 * Signature: (JISB)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnSetWaveOutputMode
  (JNIEnv *, jclass, jlong, jint, jshort, jbyte);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetWaveOutputMode
 * Signature: (JLorg/openni/OutArg;Lorg/openni/OutArg;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetWaveOutputMode
  (JNIEnv *, jclass, jlong, jobject, jobject, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnRegisterToWaveOutputModeChanges
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnRegisterToWaveOutputModeChanges
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnUnregisterFromWaveOutputModeChanges
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnUnregisterFromWaveOutputModeChanges
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetAudioMetaData
 * Signature: (JLorg/openni/AudioMetaData;)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnGetAudioMetaData
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnCreateCodec
 * Signature: (JIJLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnCreateCodec
  (JNIEnv *, jclass, jlong, jint, jlong, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetCodecID
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetCodecID
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnEncodeData
 * Signature: (JJIJILorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnEncodeData
  (JNIEnv *, jclass, jlong, jlong, jint, jlong, jint, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnDecodeData
 * Signature: (JJIJILorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnDecodeData
  (JNIEnv *, jclass, jlong, jlong, jint, jlong, jint, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnCreateRecorder
 * Signature: (JLjava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnCreateRecorder
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnSetRecorderDestination
 * Signature: (JILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnSetRecorderDestination
  (JNIEnv *, jclass, jlong, jint, jstring);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetRecorderDestination
 * Signature: (JLorg/openni/OutArg;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetRecorderDestination
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnAddNodeToRecording
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnAddNodeToRecording
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnRemoveNodeFromRecording
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnRemoveNodeFromRecording
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnRecord
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnRecord
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetRecorderFormat
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_openni_NativeMethods_xnGetRecorderFormat
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnCreatePlayer
 * Signature: (JLjava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnCreatePlayer
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnSetPlayerRepeat
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnSetPlayerRepeat
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnSetPlayerSource
 * Signature: (JILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnSetPlayerSource
  (JNIEnv *, jclass, jlong, jint, jstring);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetPlayerSource
 * Signature: (JLorg/openni/OutArg;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetPlayerSource
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnPlayerReadNext
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnPlayerReadNext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnSeekPlayerToTimeStamp
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnSeekPlayerToTimeStamp
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnSeekPlayerToFrame
 * Signature: (JLjava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnSeekPlayerToFrame
  (JNIEnv *, jclass, jlong, jstring, jint, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnTellPlayerTimestamp
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnTellPlayerTimestamp
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnTellPlayerFrame
 * Signature: (JLjava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnTellPlayerFrame
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetPlayerNumFrames
 * Signature: (JLjava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetPlayerNumFrames
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetPlayerSupportedFormat
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_openni_NativeMethods_xnGetPlayerSupportedFormat
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnEnumeratePlayerNodes
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnEnumeratePlayerNodes
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnIsPlayerAtEOF
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openni_NativeMethods_xnIsPlayerAtEOF
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnRegisterToEndOfFileReached
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnRegisterToEndOfFileReached
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnUnregisterFromEndOfFileReached
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openni_NativeMethods_xnUnregisterFromEndOfFileReached
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnSetPlaybackSpeed
 * Signature: (JD)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnSetPlaybackSpeed
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetPlaybackSpeed
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_openni_NativeMethods_xnGetPlaybackSpeed
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnCreateScriptNode
 * Signature: (JLjava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnCreateScriptNode
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnScriptNodeGetSupportedFormat
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_openni_NativeMethods_xnScriptNodeGetSupportedFormat
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnLoadScriptFromFile
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnLoadScriptFromFile
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnLoadScriptFromString
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnLoadScriptFromString
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnScriptNodeRun
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnScriptNodeRun
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnProductionNodeTypeToString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_openni_NativeMethods_xnProductionNodeTypeToString
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnResolutionGetXRes
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnResolutionGetXRes
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnResolutionGetYRes
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnResolutionGetYRes
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnResolutionGetFromXYRes
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnResolutionGetFromXYRes
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnResolutionGetFromName
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnResolutionGetFromName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnResolutionGetName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_openni_NativeMethods_xnResolutionGetName
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetVersion
 * Signature: (Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetVersion
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnIsTypeGenerator
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openni_NativeMethods_xnIsTypeGenerator
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnIsTypeDerivedFrom
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openni_NativeMethods_xnIsTypeDerivedFrom
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_openni_NativeMethods
 * Method:    xnGetBytesPerPixelForPixelFormat
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_openni_NativeMethods_xnGetBytesPerPixelForPixelFormat
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
